### ISSUE TITLE
Bulk delete not working

### ISSUE THREAD

**Issue by kerlama** [Ethan3600/EthanYehuda_CronjobManager#123]
**Describe the bug**
If you select all jobs on grid and then click delete only 20 (or which limit you set) will be removed.

**To Reproduce**
1. Go to Cron job Dashboard
2. From dropdown in first column in the grid, click select all
3. From action dropdown select delete

**Expected behavior**
All should be removed but only displayed number will be.

**Environment (please complete the following information):**
 - Browser chrome
 - Cron Job Manager Version 1.8.1
 - Magento Version 2.3.1
 - PHP Version 7.1.29

**Comment by Ethan3600** [comment]
@kerlama Sorry for late response! Unfortunately, this seems to be a bug that was introduced in Magneto 2.3.1 (as the select all was working perfectly fine on 2.3.0).

Here's an open issue on Magento's github repository: https://github.com/magento/magento2/issues/12594

Going to close this out since this is a Magento bug.
