### ISSUE TITLE
PID is not saved permanently

### ISSUE THREAD

**Issue by schmengler** [Ethan3600/EthanYehuda_CronjobManager#126]
**Describe the bug**
The PID is not saved permanently. The reason is that it is set together with the "running" status in an atomic database operation, but not saved in the schedule model. When the job is finished, the schedule model is saved, but now with empty PID value.

**To Reproduce**
1. Go to Job Dashboard
2. See empty values in PID column

**Expected behavior**
The process ids of finished jobs should be visible

**Environment (please complete the following information):**
 - Cron Job Manager Version 1.8.1
 - Magento Version 2.2.9

**Comment by ivanaugustobd** [comment]
Just to be sure, in which commit this was fixed? Because it seems to be happening again with the latest (1.13) version

**Comment by fredden** [comment]
> Just to be sure, in which commit this was fixed? Because it seems to be happening again with the latest (1.13) version

@ivanaugustobd, according to https://github.com/Ethan3600/magento2-CronjobManager/pull/125#issuecomment-509319411, this was fixed in https://github.com/Ethan3600/magento2-CronjobManager/pull/125/commits/dfa45511def81cda4fd75829a4bc0e930b459f17, which was merged as part of https://github.com/Ethan3600/magento2-CronjobManager/pull/125 (in https://github.com/Ethan3600/magento2-CronjobManager/commit/aa224218070d4d88a4bf99de5b3e885acef21aec) and https://github.com/Ethan3600/magento2-CronjobManager/pull/127 (in https://github.com/Ethan3600/magento2-CronjobManager/commit/729718a8656a24f18d86e96c9716e5c912b062bd) and released as part of version [`1.9.0`](https://github.com/Ethan3600/magento2-CronjobManager/releases/tag/v1.9.0).

**Comment by ivanaugustobd** [comment]
Yeah, actually it only occurs if you use direct cron execution through `magerun2 sys:cron:run`. But as this is a third-party tool I think it can't be considered a bug. Using native `bin/magento cron:run` it works as expected.

**Comment by fredden** [comment]
It looks like `n98-magerun2` does not call `tryLockJob()`, which is the method that this module is plugging into.
https://github.com/netz98/n98-magerun2/blob/9fdcec4033207f82a4d3e904c8454defbff2a5bf/src/N98/Magento/Command/System/Cron/RunCommand.php#L57-L78

Adding compatibility for this use-case to this module may be tricky. Please open a new issue either here or on the `n98-magerun2` repository if you'd like to explore/discuss that further.
