### ISSUE TITLE
Add Total time column in the management grid

### ISSUE THREAD

**Issue by onlinebizsoft** [Ethan3600/EthanYehuda_CronjobManager#194]
**Goal :** Have an overview which cron job takes time
**Proposal :** This column can be calculated from start time and end time

**Comment by fredden** [comment]
There's already a "Duration (seconds)" column. This was added in https://github.com/Ethan3600/magento2-CronjobManager/pull/149, which landed in version `1.11.0`. The column is intentionally a number so that the filter can be used to find things that are long-running (eg, set 'from' to `60` to find anything that takes a minute or more) and the column sort to be sensible.

Ref: https://github.com/Ethan3600/magento2-CronjobManager/commit/fb04d792aa9865838339f6d66d44e601e9380936

https://github.com/Ethan3600/magento2-CronjobManager/blob/78cb080b279519643236266b34dea4c304cbb9f9/view/adminhtml/ui_component/cronjobmanager_manage_grid.xml#L250

![Screenshot_2023-03-16_14-59-05](https://user-images.githubusercontent.com/334786/225658132-e1cff0aa-b6a5-4606-a655-e900500d20aa.png)

**Comment by onlinebizsoft** [comment]
@fredden thanks for very fast response, it would be great if we can update the detail for each screen in the readme or change the screenshot here
https://github.com/Ethan3600/magento2-CronjobManager

**Comment by fredden** [comment]
I've updated the screen-shot in the README in https://github.com/Ethan3600/magento2-CronjobManager/commit/0556da1fa3af469d08c1c9c4689b55cd5cc86d36.
