### ISSUE TITLE
After installation, the static files are not being built correctly 404

### ISSUE THREAD

**Issue by shayzalman** [Ethan3600/EthanYehuda_CronjobManager#64]
Hi Ethen
The module looks great!!

I get this issue:
After installation, the static files are not being built correctly.
**Its building:**
pub/static/adminhtml/Magento/backend/en_US/EthanYehuda_CronjobManager/template..
**and looking for:**
pub/static/adminhtml/Magento/backend/en_US/cronjobManager/template..

I get 404 on the html requests

**Comment by Ethan3600** [comment]
Hi @joomi thank you for using the CJM!

Can you give me some more details?

* What version of Magento and the CJM are you using?

* What commands are you using to create static content?

    * guessing this: `php bin/magento setup:static-content:deploy -t Magento/backend` but want to be sure

* What mode is Magento in? Developer or Production?

**Comment by shayzalman** [comment]
Hi
The Magento ver. is .2.2.2
I'm on developer mode (getting the same 404 error before try to deploy static-content)
After running php bin/magento setup:static-content:deploy -t Magento/backend (getting 404)
(renaming the folder manually solved the problem, and I could see the module running)

**Comment by Ethan3600** [comment]
I'm having a hard time reproducing this. 

Do you have anything outside the ordinary configuration that could cause this? (kind of a shot in the dark)

> Are you versioning static content?

What version of the Cron Job Manager are you using?

Modifications to .htaccess? URL rewrites? Custom code?

> Do you have an .htaccess in pub/ and in pub/static/?

Does this happen on a clean install of Magento 2.2.2? (that's the environment I'm working in)

What happens if you `rm -rf pub/static/adminhtml/Magento/backend/en_US/EthanYehuda_CronjobManager` and go on the dashboard or timeline? What symlink paths does it generate  in developer mode?

Couldn't find anything on stack overflow that relates to this issue besides these two:

* https://magento.stackexchange.com/questions/211325/static-files-not-available-in-developer-mode

* https://magento.stackexchange.com/questions/160474/magento2-wrong-path-of-static-contents/160489#160489

But neither of them resemble your issue very much...

Need some more details to help me reproduce this. Sorry for the inconvenience.

**Comment by Ethan3600** [comment]
@joomi I'm going to close this issue since I haven't got a response in a while.  Feel free to comment on it, and I'll reopen.

**Comment by kirkmadera** [comment]
I am running into this also in Production mode. We have run into similar issues before and think this is due to production mode not respecting the "[paths](https://requirejs.org/docs/api.html#config-paths)" key in requirejs config. I am running Magento 2.2.5. 

This is the error in the console:
`[2018-09-18 03:06:21] [ERROR] Failed to load the "cronjobManager/timeline/timeline" template requested by "cronjobmanager_timeline.cronjobmanager_timeline.timeline_container".`

Our build process is basically this:

1. Clone the repo
2. Run composer install `composer install --optimize-autoloader`
3. Set production mode
4. Compile di `bin/magento setup:di:compile`
5. Deploy static content `bin/magento setup:static-content:deploy`

I also can confirm that the files get built out with the path "EthanYehuda_CronjobManager/templates" instead of "cronjobManager/template". The admin, however, is trying to load them with the "cronjobManager/template" URL.

I don't see mention of support for the "paths" in M2 documentation:
- https://devdocs.magento.com/guides/v2.2/javascript-dev-guide/javascript/js-resources.html
- https://devdocs.magento.com/guides/v2.0/javascript-dev-guide/javascript/requirejs_concept.html

(Note: Their docs are broken and interlink between versions. There was no 2.2 version of the requirejs_concept.html)

I think this could probably be fixed by switching to map instead of paths.

**Comment by Ethan3600** [comment]
Fixed in v1.6.3
