### ISSUE TITLE
Ethan3600/magento2-CronjobManager

### ISSUE THREAD

**Issue by rohitkrjaiswal** [Ethan3600/EthanYehuda_CronjobManager#75]
hi;
i had created new cron on localhost under add new cron , and i have scheduled under job configuration for every 1 min ,
in that module there is a code to print in the logger in every 1 min,but the scheduler to dont run.
and if i use dispatch now then it runs only once.
let me know how to run for every min on localhost.

Thanks.

**Comment by Ethan3600** [comment]
I'm struggling to understand what the issue is. It sounds like your crontab configurations aren't setup?
Are other crons running?

The dispatch button is supposed to run the cron immediately, so that's expected.

Just to clarify what the "add" button does, it just adds an _existing_ cron job to the queue.

One way to check if your crons are running is to look on the timeline. Maybe all crons aren't running?

If that's not the issue, then please provide steps for me to reproduce the problem!

Thanks for using the CJM!

**Comment by Ethan3600** [comment]
@rohitkrjaiswal I'm going to close this issue since I haven't heard from you. Please feel free to comment again and I'll re-open!
